name: Generate Language Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "" 
          plugin_languages: yes
          plugin_languages_limit: 8 # Menampilkan hingga 8 bahasa agar detail
          plugin_languages_details: percentage # Dibuat lebih ringkas tanpa byte size
          config_transparent: yes
