name: Generate Language Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "" 
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage
          
          # Baris baru: Mengabaikan HTML & CSS agar Dart/PHP naik
          plugin_languages_ignored: html, css
          
          config_transparent: yes
